### ISSUE TITLE
Thumbnail üzerindeki ögelerin dengesizliği

### ISSUE THREAD

**Issue by zeusminus** [Sibyl666/osuTurkey-Thumbnail#1]
Mevcut thumbnail çalışmasını beğensem de "acc", "combo" ve "pp" üçlüsünün sağ tarafta bulunmasını tercih ederim.

## Mevcut thumbnail
![](https://zeu.s-ul.eu/tk87xHOQ.png)

## Önerdiğim thumbnail
![](https://zeu.s-ul.eu/4t5OnP7I.png)

Yukarıdaki resimlerden anlaşılacağı gibi, sağa kayırdığımızda mevcut yazıların bütünlüğü bir paralel kenar oluşturmakta, böylece estetik anlayışa katkıda bulunmaktadır. Bu doğrultuda gerekli değişikliğin yapılmasını arz ediyorum.

---

Edit: Ayrıca ikinci görsel için sol-üstte bulunan boşluğa kanalın logosunu da yerleştirebilirsin. Hoş durabilir.

**Comment by Sibyl666** [comment]
Mod ikonları olmadan acc combo pp üçlüsünü sağa alınca daha güzel gözüküyor dediğin gibi ama mod ikonlarını ekleyince o kadar da bi fark göremiyorum sanki eskisine göre. Genel olarak güzel bi öneri yapmışsın sağa almayı düşünebilirim aklımda kalsın.

Sol üstte bulunan köşeye kanal ikonu eklemeyi düşünmüyorum çünkü zaten thumbnaili kullanan tek kanal osu Türkiye. Thumbnailde gereksiz kalabalık oluşturmaya gerek yok
![thumbnail](https://user-images.githubusercontent.com/54271295/112692415-f19d0880-8e8f-11eb-8cb2-114d260b1d5a.png)
Edit: Font boyutlarında bazı farklılıklar olabilir ve scripte geçirdiğimden kaynaklı. 100% accurate yapmak zor iş

**Comment by Sibyl666** [comment]
Sağa aldım bu üçlüyü dediğin gibi kalsın bu şekilde bakalım
![image](https://user-images.githubusercontent.com/54271295/112724757-e72d4e00-8f25-11eb-8ea3-303c6dd481bf.png)
